### ISSUE TITLE
解析Header時, Cell沒有值會引發Null錯誤

### ISSUE THREAD

**Issue by samliu319** [shps951023/MiniExcel#137]
![Snipaste_2021-03-31_20-44-41](https://user-images.githubusercontent.com/1710990/113146179-f122ba00-9261-11eb-9e82-d9397c483ade.png)

![Snipaste_2021-03-31_20-46-01](https://user-images.githubusercontent.com/1710990/113146342-20392b80-9262-11eb-8309-dcdb82693750.png)

**Comment by shps951023** [comment]
因為系統認定 Z1欄位有值，所以A1-Z1都應該有值當表頭

我會針對這個問題修改成
方案1. 增加明確 exception 說明不能中間有空值
方案2. 遇到空值就認定結束，以上圖利子，表頭解析在X1遇到空值，就會認定表頭只有A1-X1

**Comment by samliu319** [comment]
看能不能遇到空值時, 
那欄跳過不處理就好,
因為我也有特殊的表格中間很多空格的,
但空格後有表頭的欄位還是會用上,
感謝

**Comment by shps951023** [comment]
0.10.0 版本解決此問題，麻煩有問題再告知，謝謝 😉
