### ISSUE TITLE
能否在 Gitee 中开库并同步代码

### ISSUE THREAD

**Issue by MonkSoul** [shps951023/MiniExcel#146]
您好，我是 Furion 框架作者百小僧：https://gitee.com/dotnetchina/Furion

是这样的，我在好些天前就注意您这个库，个人觉得写的很不错，是一匹黑马库，所以希望您这个库能在 Gitee 中同步一份代码，另外想邀请您加入 dotNET China 组织：[https://gitee.com/dotnetchina](https://gitee.com/dotnetchina)，不知您意下如何。

我也打算推出 Furion 框架的您这个库拓展。

**Comment by MonkSoul** [comment]
并非打广告，而是真心邀请您，您可以看看我们的组织，不管您决定如何，都支持您这个库。

**Comment by shps951023** [comment]
@MonkSoul 
您好,我刚才在 Gitee 开了仓 :  [暐翰/MiniExcel](https://gitee.com/shps951023/MiniExcel#https://github.com/shps951023/MiniExcel/blob/master/README.zh-Hans.md) 
方便有时 Github 会卡的朋友

也欢迎跟感谢任何扩展 😉

能加入改组织, 您的 Furion 跟其他前辈做的 SqlSugar ORM 跟 OpenAuth.Net 我目前都有使用在项目中

**Comment by MonkSoul** [comment]
感谢感谢。
