### ISSUE TITLE
Can SaveAs support iDataReader export to avoid the dataTable consuming too much memory

### ISSUE THREAD

**Issue by yfl8910** [shps951023/MiniExcel#211]

**Comment by yfl8910** [comment]
epplus is support  ws.Cells["A1"].LoadFromDataReader(reader, true)，if this project is support DataReader ， it will much better ，thanks

**Comment by shps951023** [comment]
Thanks, MiniExcel will support this feature.

**Comment by shps951023** [comment]
![image](https://user-images.githubusercontent.com/12729184/116056074-f54ec580-a6af-11eb-8010-111252f7102e.png)
![image](https://user-images.githubusercontent.com/12729184/116056107-fc75d380-a6af-11eb-8fd5-8439e0358370.png)

**Comment by shps951023** [comment]
Because the dimension needs to be placed in the header + the reason for the dimension size is only known after reading, so it needs to be rewritten once
![image](https://user-images.githubusercontent.com/12729184/116058547-89ba2780-a6b2-11eb-942c-b56fefbd0987.png)

**Comment by shps951023** [comment]
v 0.13.5 support this

```csharp
MiniExcel.SaveAs(path, reader);
```
