### ISSUE TITLE
comma delim column

### ISSUE THREAD

**Issue by RejectKid** [shps951023/MiniExcel#247]
if I have data in a column as such

commaDelimColumn
"data1, data2, data3"

i cannot read this in as a List<string>.  is there a way to do this?

**Comment by shps951023** [comment]
csv or xlsx ?  

I can read result as List
![image](https://user-images.githubusercontent.com/12729184/119472487-df025b00-bd7c-11eb-81e1-a3116d4d14f0.png)

**Comment by RejectKid** [comment]
![image](https://user-images.githubusercontent.com/6117898/119506203-b0b05b80-bd3b-11eb-828e-951afff8f20a.png)

I dont have the .Dump() so idk where thats in?  but its an xlsx.

**Comment by shps951023** [comment]
Can you provide me this file for confirmation?

**Comment by RejectKid** [comment]
[Test.xlsx](https://github.com/shps951023/MiniExcel/files/6548098/Test.xlsx)

**Comment by shps951023** [comment]
@RejectKid 

Is below result like your expected?

![image](https://user-images.githubusercontent.com/12729184/119746243-95238d00-bec2-11eb-8ce8-345bb5a43a13.png)

```c#
	var path = @"C:\Users\Wei\Downloads\Test.xlsx";
	var rows = MiniExcel.Query(path,true).Cast<IDictionary<string,object>>().ToList();
	
	foreach (var r in rows)
	{
		var commaDelim = (r["CommaDelimData"] as string).Split(',').ToList();
		r["CommaDelimData"] = commaDelim;
	}
```

**Comment by RejectKid** [comment]
ah ha yeah thats the result.  it seems ill need to manipulate data and re-set property to that.  wasnt sure if there was a built in way to miniExcel to do

**Comment by shps951023** [comment]
Yes, you need to re-set value.
