### ISSUE TITLE
怎么去使用

### ISSUE THREAD

**Issue by zzmnihao** [shps951023/MiniExcel#278]
### Excel Type

- [ ] XLSX
- [ ] XLSM
- [ ] CSV
- [ ] OTHER

### Upload Excel File

Please attach your issue file by dragging or droppng, selecting or pasting them.

e.g : [https://github.com/shps951023/MiniExcel/files/6538107/demo.xlsx](https://github.com/shps951023/MiniExcel/files/6538107/demo.xlsx)

**Comment by shps951023** [comment]
可以看Readme快速开始，有中文版 https://github.com/shps951023/MiniExcel/blob/master/README.zh-CN.md
