### ISSUE TITLE
Create Multiple Sheets from IDataReader have Bug

### ISSUE THREAD

**Issue by yfl8910** [shps951023/MiniExcel#283]
### Create Multiple Sheets from IDataReader  have Bug

          System.InvalidOperationException: 'The connection was not closed. The connection's current state is open.'

         Reference code:

                var sheets = new Dictionary<string, object> {};

                foreach (var table in tableNames)
                {
                    string sql = BuildSQl.GetSQLfromTable(table, dbtype);
                    IDataReader reader = dbAccess.GetDataReader(sql);
                    sheets.Add(table, reader);
                }
                MiniExcel.SaveAs(newFile.ToString(), sheets);

**Comment by shps951023** [comment]
![image](https://user-images.githubusercontent.com/12729184/133041140-e4a3251e-f4c7-447a-9c24-5d0a2a52bf0e.png)
![image](https://user-images.githubusercontent.com/12729184/133041163-b677d309-ec97-4fb3-85d3-f7d2426f97ff.png)
![image](https://user-images.githubusercontent.com/12729184/133041189-00ac8c45-6c34-4728-b402-783ed999dea7.png)

**Comment by shps951023** [comment]
It's work
![1a34f555fc6af98a9290cb1c11e7743](https://user-images.githubusercontent.com/12729184/133114005-b7b41dc0-d7c1-4048-940e-48d79c95c8b8.png)

**Comment by shps951023** [comment]
![image](https://user-images.githubusercontent.com/12729184/133206190-4386113c-68a0-4c98-a57d-70e224cb7c2b.png)
```
public IDataReader GetDataReader(string strSql)
  {
      SqlCommand cmd = new SqlCommand(strSql, (SqlConnection)conn)
      {
          CommandTimeout = 10000
      };
      if (IsTran)
      {
          cmd.Transaction = (SqlTransaction)tran;
      }

      cmd.CommandTimeout = 10000;
      try
      {              
          conn.Open();             
          SqlDataReader myReader = cmd.ExecuteReader(CommandBehavior.CloseConnection);
          return myReader;
      }
      catch (System.Data.SqlClient.SqlException e)
      {
          throw e;
      }
  }
```
