### ISSUE TITLE
转化错误的建议(type conversion error)

### ISSUE THREAD

**Issue by ping9719** [shps951023/MiniExcel#309]
## 我的文档：
![image](https://user-images.githubusercontent.com/9651046/143804246-8c8ecd69-8ece-4971-b76a-bd99a383b612.png)
## 用户在输入错误的数据，我得到的错误不是我想要的：
![image](https://user-images.githubusercontent.com/9651046/143804296-f350c5e9-c95b-497f-9abf-7a581e870387.png)
## 你的错误类型为（InvalidCastException：SystemException）
![image](https://user-images.githubusercontent.com/9651046/143804396-9d232bc1-eef6-4743-8ee3-4feed684df72.png)
## 我希望可以你自建一个错误类型，提取出关键的错误信息（ExcelInvalidCastException:InvalidCastException）
![image](https://user-images.githubusercontent.com/9651046/143804785-acf16f05-85c4-4ad1-b802-5cb8150170ae.png)
## 然后你抛出ExcelInvalidCastException，不抛出InvalidCastException，这样子对向右代码没有影响(可能需要重写tostring())，我也可以获取ColumnName,CellRow....

**Comment by shps951023** [comment]
@ping9719 
![image](https://user-images.githubusercontent.com/12729184/150618471-f57a3c65-fa15-4839-a761-3f7f61690a7a.png)
感谢你完整的逻辑提供!
V0.21.0 会支持 ExcelInvalidCastException
