### ISSUE TITLE
Question. How to do floating-point formatting?

### ISSUE THREAD

**Issue by wootapa** [shps951023/MiniExcel#312]
I've tried to render floating point types in xlsx using typed objects with type double/decimal but it always renders as integer. How can we control decimal precision? I've tried the ExcelFormatAttribute but it seems to be exclusive for date's.

**Comment by shps951023** [comment]
Hi @wootapa 
Yes, now MiniExcel doesn't support this, maybe next version could support this.

**Comment by wootapa** [comment]
Sounds great. Thanks!
