### ISSUE TITLE
CultureInfo support

### ISSUE THREAD

**Issue by wootapa** [shps951023/MiniExcel#316]
If we could pass an optional `CultureInfo` as argument to `Query` to be used during parsing, it would allow clients to pass streams from different locales other than what is currently the default. Ex:
```csharp
MiniExcel.Query<T>(defaultStream); // -> Use current culture
MiniExcel.Query<T>(englishStream, culture: CultureInfo.GetCultureInfo("en-GB")); // Use passed culture
```

Thanks for your great work! :thumbsup:

**Comment by shps951023** [comment]
@wootapa v1.22.0 support this feature
