### ISSUE TITLE
文档中查询数据以第一行数据当Key 案例问题，案例测试无法通过

### ISSUE THREAD

**Issue by RicardoQuan** [shps951023/MiniExcel#336]
### Excel Type

- [ ] XLSX
- [ ] XLSM
- [ ] CSV
- [ ] OTHER

### Upload Excel File

Please attach your issue file by dragging or droppng, selecting or pasting them.

e.g : [https://github.com/shps951023/MiniExcel/files/6538107/demo.xlsx](https://github.com/shps951023/MiniExcel/files/6538107/demo.xlsx)

**Comment by shps951023** [comment]
@RicardoQuan 
请提供完整代码、逻辑、文件
