### ISSUE TITLE
Excel was unable to open the file

### ISSUE THREAD

**Issue by tvanzeleDelen** [shps951023/MiniExcel#343]
### Excel Type

- [ ] XLSX

### Upload Excel File
[20221703_dsp-interfincomm-swiftincoming-prod.xlsx](https://github.com/shps951023/MiniExcel/files/8284442/20221703_dsp-interfincomm-swiftincoming-prod.xlsx)

Please attach your issue file by dragging or droppng, selecting or pasting them.

e.g : [https://github.com/shps951023/MiniExcel/files/6538107/demo.xlsx](https://github.com/shps951023/MiniExcel/files/6538107/demo.xlsx)

### MiniExcel Version
1.24.1 

### Description
I generated an excel workbook with multiple tabs from various SQLDataReaders. When I open this file, I get an error that the file is corrupted and should be repaired. After repair all tabs and content seems to be there.
Error in Exel:
<recoveryLog xmlns=http://schemas.openxmlformats.org/spreadsheetml/2006/main><logFileName>error152440_01.xml</logFileName><summary>Errors were detected in file 'C:\Users\local_tomzel\INetCache\Content.Outlook\8YLC4TFG\20221703_dsp-interfincomm-swiftoutgoing-prod.xlsx'</summary><additionalInfo><info>Excel completed file level validation and repair. Some parts of this workbook may have been repaired or discarded.</info></additionalInfo><repairedRecords><repairedRecord>Repaired Records: Cell information from /xl/worksheets/sheet9.xml part</repairedRecord><repairedRecord>Repaired Records: Cell information from /xl/worksheets/sheet10.xml part</repairedRecord><repairedRecord>Repaired Records: Cell information from /xl/worksheets/sheet11.xml part</repairedRecord></repairedRecords></recoveryLog>

**Comment by shps951023** [comment]
@tvanzeleDelen 
Could you provide your code logic? and the input value

**Comment by tvanzeleDelen** [comment]
This is the code I use, it receives a dynamic list of queries to be executed. The resulting text file was attached in the first ticket.
try
                {
                    SqlDataReader rules = SQLHelper.GetSqlDataReader(SQL);
                    var sheets = new Dictionary<string, object>();
                    while (rules.Read())
                    {
                        logger.Debug("Generating sheet " + rules.GetString(0));
                        sheets.Add(rules.GetString(0), SQLHelper.GetSqlDataReader(ConnectionStringTargetDatabase, rules.GetString(1), 120));
                    }
                    using (var stream = File.Create(strReportLocation))MiniExcel.SaveAs(stream, sheets);
                    //MiniExcel.SaveAs(strReportLocation, sheets);
                    strReturn = strReportLocation;
                    General.WaitSeconds(30);
                }

**Comment by shps951023** [comment]
@tvanzeleDelen 
Thank you, v1.24.3 fixed this bug

**Comment by tvanzeleDelen** [comment]
Tested and fixed.
Thank you.
